"""initial schema

Revision ID: 99701a023683
Revises: 
Create Date: 2026-04-06 10:49:27.401809
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99701a023683'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosage_instructions',
    sa.Column('text_en', sa.String(length=255), nullable=False),
    sa.Column('text_ar', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigation_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('reference_range', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications_master',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('default_dosage', sa.String(length=100), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('interactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_master_name'), 'medications_master', ['name'], unique=False)
    op.create_table('patients',
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('full_name_ar', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sex_enum'), nullable=False),
    sa.Column('marital_status', sa.Enum('single', 'married', 'divorced', 'widowed', name='marital_status_enum'), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_alt', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('smoking_status', sa.Enum('never', 'former', 'current', name='smoking_status_enum'), nullable=True),
    sa.Column('smoking_packs_day', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('doctor', 'nurse', 'receptionist', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('type', sa.Enum('new', 'follow_up', 'procedure', 'telemedicine', name='appointment_type'), server_default='follow_up', nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'confirmed', 'arrived', 'completed', 'cancelled', 'no_show', name='appointment_status'), server_default='scheduled', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_at'), 'appointments', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'login', 'logout', 'export', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('examinations',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('examined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('examined_by', sa.UUID(), nullable=False),
    sa.Column('pulse_bpm', sa.Integer(), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', name='activity_level_enum'), nullable=True),
    sa.Column('head_neck', sa.Text(), nullable=True),
    sa.Column('upper_limb', sa.Text(), nullable=True),
    sa.Column('lower_limb', sa.Text(), nullable=True),
    sa.Column('abdomen', sa.Text(), nullable=True),
    sa.Column('chest', sa.Text(), nullable=True),
    sa.Column('neurology', sa.Text(), nullable=True),
    sa.Column('cardiac_apex', sa.String(length=50), nullable=True),
    sa.Column('cardiac_s1', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cardiac_s2', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cardiac_s3', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cardiac_s4', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cardiac_murmurs', sa.Text(), nullable=True),
    sa.Column('cardiac_additional_sounds', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['examined_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examinations_patient_id'), 'examinations', ['patient_id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seen_by', sa.UUID(), nullable=False),
    sa.Column('complaint', sa.Text(), nullable=True),
    sa.Column('present_history', sa.Text(), nullable=True),
    sa.Column('pulse_bpm', sa.Integer(), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('examination', sa.Text(), nullable=True),
    sa.Column('investigation', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('next_follow_up', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['seen_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_patient_id'), 'follow_ups', ['patient_id'], unique=False)
    op.create_table('investigations',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('investigation_date', sa.Date(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('ecg_result', sa.Text(), nullable=True),
    sa.Column('stress_test', sa.Text(), nullable=True),
    sa.Column('cardiac_cath', sa.Text(), nullable=True),
    sa.Column('echo_lvedd', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('echo_lvesd', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('echo_ivs', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('echo_pwt', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('echo_fs', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('echo_ef', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('echo_ao', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('echo_la', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('echo_ao_valve', sa.Text(), nullable=True),
    sa.Column('echo_mit_valve', sa.Text(), nullable=True),
    sa.Column('echo_pulm_valve', sa.Text(), nullable=True),
    sa.Column('echo_tric_valve', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_patient_id'), 'investigations', ['patient_id'], unique=False)
    op.create_table('past_family_history',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('diabetes', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('hypertension', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rheumatic_heart_disease', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ischemic_heart_disease', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cabg', sa.Text(), nullable=True),
    sa.Column('valve_replacement', sa.Text(), nullable=True),
    sa.Column('other_conditions', sa.Text(), nullable=True),
    sa.Column('family_consanguinity', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('family_hypertension', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('family_diabetes', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('family_ihd', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('family_other', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('patient_medications',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('instructions_ar', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('prescribed_by', sa.UUID(), nullable=False),
    sa.Column('reason_stopped', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications_master.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_medications_patient_id'), 'patient_medications', ['patient_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('prescribed_by', sa.UUID(), nullable=False),
    sa.Column('prescribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'finalized', 'voided', name='prescription_status'), server_default='draft', nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_table('present_history',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('chest_pain', sa.Enum('none', 'typical', 'atypical', 'non_cardiac', name='chest_pain_type'), nullable=True),
    sa.Column('chest_pain_remarks', sa.Text(), nullable=True),
    sa.Column('dyspnea_exertional', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dyspnea_pnd', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dyspnea_orthopnea', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dyspnea_grade', sa.Integer(), nullable=True),
    sa.Column('palpitations', sa.Enum('none', 'occasional', 'frequent', 'constant', name='palpitation_frequency'), nullable=True),
    sa.Column('syncope', sa.Enum('none', 'pre_syncope', 'syncope', name='syncope_type'), nullable=True),
    sa.Column('lower_limb_edema', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('abdominal_swelling', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('low_cardiac_output_dizziness', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('low_cardiac_output_blurring', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('low_cardiac_output_fatigue', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('neurological_symptoms', sa.Text(), nullable=True),
    sa.Column('git_symptoms', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('urinary_symptoms', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('chest_symptoms', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_present_history_patient_id'), 'present_history', ['patient_id'], unique=False)
    op.create_table('images',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=True),
    sa.Column('image_type', sa.Enum('xray', 'echo', 'ecg', 'ct', 'mri', 'other', name='image_type_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('dicom_study_uid', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_patient_id'), 'images', ['patient_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('test_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('reference_range', sa.String(length=50), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_investigation_id'), 'lab_results', ['investigation_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('instructions_ar', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications_master.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_lab_results_investigation_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_images_patient_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_present_history_patient_id'), table_name='present_history')
    op.drop_table('present_history')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_patient_medications_patient_id'), table_name='patient_medications')
    op.drop_table('patient_medications')
    op.drop_table('past_family_history')
    op.drop_index(op.f('ix_investigations_patient_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_follow_ups_patient_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_examinations_patient_id'), table_name='examinations')
    op.drop_table('examinations')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_medications_master_name'), table_name='medications_master')
    op.drop_table('medications_master')
    op.drop_table('investigation_types')
    op.drop_table('dosage_instructions')
    # ### end Alembic commands ###
